
name: udhann_grok
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.9
  http: ^0.13.6
  intl: ^0.20.2
  url_launcher: ^6.3.1
  dio: ^5.7.0
  shared_preferences: ^2.2.2 # Added for token persistence

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
